/**
 * Drizzle schema (Postgres — Neon in production, PGlite locally and in tests).
 *
 * Canonical storage unit is YARDS (`double precision`) for every lie, including
 * GREEN. Feet<->yards conversion happens in exactly one place: `src/lib/units.ts`
 * (feet on write for GREEN, yards->feet on display). Nothing else in the app
 * should do that arithmetic inline. NOTE: every float here is `doublePrecision`,
 * never `real` — pg `real` is 4-byte and would corrupt fractional-yard green
 * distances and the 3-decimal SG values the tests assert.
 *
 * `sg` / `category` / `baseline_id` on `shots` are DERIVED, denormalised
 * columns — always produced by `recomputeRound()` (see
 * `src/lib/sg/recompute.ts`), never written directly by a form. Hole score
 * is likewise always derived from `shots`, never stored as its own input.
 *
 * Ids are `generated by default` (not `always`) so `scripts/migrate-sqlite-to-pg.ts`
 * can carry the original SQLite ids across.
 *
 * Ownership: `rounds.user_id` and `courses.created_by_user_id` point at the Better
 * Auth `user` table. Both are NULLABLE on purpose — rows imported from the
 * single-user SQLite era have no owner until the admin first signs in, at which
 * point `claimLegacyData()` (src/lib/auth/claim.ts) assigns them.
 */
import {
  pgTable,
  text,
  integer,
  doublePrecision,
  boolean,
  timestamp,
  uniqueIndex,
  index,
  primaryKey,
} from 'drizzle-orm/pg-core';

// ---------------------------------------------------------------------------
// Auth (Better Auth core tables — names/shape per its Drizzle adapter)
// ---------------------------------------------------------------------------

export const user = pgTable('user', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: boolean('email_verified').notNull().default(false),
  image: text('image'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
});

export const session = pgTable(
  'session',
  {
    id: text('id').primaryKey(),
    expiresAt: timestamp('expires_at').notNull(),
    token: text('token').notNull().unique(),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
  },
  (t) => ({ userIdx: index('session_user_id_idx').on(t.userId) }),
);

export const account = pgTable(
  'account',
  {
    id: text('id').primaryKey(),
    accountId: text('account_id').notNull(),
    providerId: text('provider_id').notNull(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    accessToken: text('access_token'),
    refreshToken: text('refresh_token'),
    idToken: text('id_token'),
    accessTokenExpiresAt: timestamp('access_token_expires_at'),
    refreshTokenExpiresAt: timestamp('refresh_token_expires_at'),
    scope: text('scope'),
    password: text('password'),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (t) => ({ userIdx: index('account_user_id_idx').on(t.userId) }),
);

export const verification = pgTable(
  'verification',
  {
    id: text('id').primaryKey(),
    identifier: text('identifier').notNull(),
    value: text('value').notNull(),
    expiresAt: timestamp('expires_at').notNull(),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (t) => ({ identifierIdx: index('verification_identifier_idx').on(t.identifier) }),
);

// ---------------------------------------------------------------------------
// Golf data
// ---------------------------------------------------------------------------

export const courses = pgTable('courses', {
  id: integer('id').primaryKey().generatedByDefaultAsIdentity(),
  name: text('name').notNull(),
  location: text('location'),
  // Who added the course (they, and the admin, may edit it). Null = seeded / legacy.
  createdByUserId: text('created_by_user_id').references(() => user.id, { onDelete: 'set null' }),
  // Its entry in the course directory (src/lib/directory, e.g. 'osm:way/123'), set by the admin.
  // A round here then counts the directory course as played. Null = not linked yet.
  directoryKey: text('directory_key'),
});

export const tees = pgTable(
  'tees',
  {
    id: integer('id').primaryKey().generatedByDefaultAsIdentity(),
    courseId: integer('course_id')
      .notNull()
      .references(() => courses.id),
    name: text('name').notNull(),
    gender: text('gender').notNull(), // 'M' | 'F'
    distanceUnit: text('distance_unit').notNull(), // 'yards' | 'metres'
    courseRating: doublePrecision('course_rating'), // nullable — not every card publishes one
    slopeRating: doublePrecision('slope_rating'),
    // Reference totals used as the editor's "does this still add up" check
    // and (at import/seed time) as the checksum target. Not re-derived on
    // every read — they're the club-card truth the grid is checked against.
    expectedTotalYards: doublePrecision('expected_total_yards'),
    expectedPar: integer('expected_par'),
  },
  (table) => ({
    courseTeeUnique: uniqueIndex('tees_course_id_name_unique').on(table.courseId, table.name),
  }),
);

export const teeHoles = pgTable(
  'tee_holes',
  {
    id: integer('id').primaryKey().generatedByDefaultAsIdentity(),
    teeId: integer('tee_id')
      .notNull()
      .references(() => tees.id),
    holeNo: integer('hole_no').notNull(),
    par: integer('par').notNull(),
    strokeIndex: integer('stroke_index'), // nullable — not every card publishes one
    yards: doublePrecision('yards').notNull(),
  },
  (table) => ({
    teeHoleUnique: uniqueIndex('tee_holes_tee_id_hole_no_unique').on(table.teeId, table.holeNo),
  }),
);

export const rounds = pgTable(
  'rounds',
  {
    id: integer('id').primaryKey().generatedByDefaultAsIdentity(),
    // Owner. Nullable only for legacy rows awaiting claimLegacyData(); every new round sets it.
    userId: text('user_id').references(() => user.id, { onDelete: 'cascade' }),
    courseId: integer('course_id')
      .notNull()
      .references(() => courses.id),
    teeId: integer('tee_id')
      .notNull()
      .references(() => tees.id),
    playedOn: text('played_on').notNull(), // ISO date (YYYY-MM-DD) — portable, sortable as text
    weather: text('weather'),
    // Free-text round commentary (typed, or a dictated/transcribed voice note). Owner-only.
    notes: text('notes'),
    // Optional human label, e.g. "Medal Final 2026". Null falls back to course/date in the UI.
    name: text('name'),
    // Overall mentality/feel for the round, each 1 (poor) – 5 (excellent); null = not rated.
    // Pia Nilsson's balance / tempo / tension. For tension, 5 = relaxed (low tension), so
    // every scale reads "higher is better". Validated in src/lib/rounds/details.ts, not by a
    // DB CHECK. Owner-only, like `notes`.
    // Optional playing handicap for this round (what the card was played off). With it — and a
    // full set of stroke indexes on the tee — the scorecard shows net score and Stableford points.
    // Negative = a plus handicap. Validated in src/lib/rounds/details.ts.
    playingHandicap: integer('playing_handicap'),
    // Chosen when the round is started: Brief or Detailed analysis. Detailed (true) = the optional
    // per-shot inputs (focus/commitment, miss direction, putt slope/break) and balance/tempo/tension
    // are open by default; Brief (false) = collapsed but still expandable. Defaults to true so rounds
    // from before this option keep their inputs open.
    // The DB column keeps its original name, `track_mentality` (it first covered mentality only):
    // same meaning, so renaming it would be a migration with nothing to gain.
    detailedEntry: boolean('track_mentality').notNull().default(true),
    mentalBalance: integer('mental_balance'),
    mentalTempo: integer('mental_tempo'),
    mentalTension: integer('mental_tension'),
    // LEGACY: the first mentality design (confidence / focus / composure). No longer shown or
    // written; kept only so already-saved values aren't destroyed by a migration.
    mentalConfidence: integer('mental_confidence'),
    mentalFocus: integer('mental_focus'),
    mentalComposure: integer('mental_composure'),
  },
  (t) => ({ userIdx: index('rounds_user_id_idx').on(t.userId) }),
);

export const shots = pgTable(
  'shots',
  {
    id: integer('id').primaryKey().generatedByDefaultAsIdentity(),
    roundId: integer('round_id')
      .notNull()
      .references(() => rounds.id, { onDelete: 'cascade' }),
    holeNo: integer('hole_no').notNull(),
    shotNo: integer('shot_no').notNull(),
    startLie: text('start_lie').notNull(),
    startYards: doublePrecision('start_yards').notNull(),
    endLie: text('end_lie'), // nullable — null when holed
    endYards: doublePrecision('end_yards').notNull(),
    holed: boolean('holed').notNull(),
    penaltyStrokes: integer('penalty_strokes').notNull().default(0),
    penaltyType: text('penalty_type'), // nullable: 'LATERAL' | 'STROKE_AND_DISTANCE'

    // Derived — see recomputeRound(). Nullable only for the instant between
    // insert and the recompute call that always follows it in the same
    // mutation.
    sg: doublePrecision('sg'),
    category: text('category'),
    bunkerSubtype: text('bunker_subtype'),
    baselineId: text('baseline_id'),

    // Optional per-shot mentality tags, entered by the user (never derived).
    // 'INTERNAL' (swing thoughts / mechanics) | 'EXTERNAL' (target / feel); null = not recorded.
    focus: text('focus'),
    // 'COMMITTED' (clear decision, fully committed) | 'HESITANT'; null = not recorded.
    commitment: text('commitment'),

    // Optional shot-shape tags, entered by the user (never derived, never feed SG). Validated in
    // src/lib/rounds/entry.ts (values) and normaliseShotTags (which tags apply to which shot).
    // Where the shot FINISHED relative to the target: 'LEFT' | 'RIGHT' | 'LONG' | 'SHORT'.
    // Tee shots on par 4/5: LEFT/RIGHT of the fairway only (fairway hit = null). Putts: where a
    // MISSED putt finished; its high/low side is derived from `putt_break`, not stored.
    missDirection: text('miss_direction'),
    // Putts only. 'UPHILL' | 'DOWNHILL' | 'FLAT'
    puttSlope: text('putt_slope'),
    // Putts only. 'LEFT_TO_RIGHT' | 'RIGHT_TO_LEFT' | 'STRAIGHT'
    puttBreak: text('putt_break'),
  },
  (table) => ({
    roundHoleShotUnique: uniqueIndex('shots_round_id_hole_no_shot_no_unique').on(
      table.roundId,
      table.holeNo,
      table.shotNo,
    ),
  }),
);

/**
 * Emails pre-authorised to create an account, recorded when someone with a valid invite cookie
 * asks for a magic link. The emailed link is often opened in a DIFFERENT browser (a mail app's
 * in-app browser), where the invite cookie doesn't exist — without this the sign-up gate would
 * reject a perfectly good invite. Rows are only ever added for an address that already proved it
 * had the invite.
 */
export const invitedEmails = pgTable('invited_emails', {
  /** Lower-cased. */
  email: text('email').primaryKey(),
  invitedAt: timestamp('invited_at').notNull().defaultNow(),
});

/** "Please add my course" — raised by any player, worked through by the admin. */
export const courseRequests = pgTable(
  'course_requests',
  {
    id: integer('id').primaryKey().generatedByDefaultAsIdentity(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    courseName: text('course_name').notNull(),
    // Free text: where it is, which tees they play, a scorecard link — anything that helps.
    details: text('details'),
    status: text('status').notNull().default('open'), // 'open' | 'done'
    createdAt: timestamp('created_at').notNull().defaultNow(),
  },
  (t) => ({ statusIdx: index('course_requests_status_idx').on(t.status) }),
);

/**
 * Courses a player has ticked off as played — any course in the directory, whether or not it has a
 * scorecard here. `course_key` is a directory key (src/lib/directory), not a foreign key: the
 * directory is a static file. Courses with a logged round count as played without a row here.
 */
export const playedCourses = pgTable(
  'played_courses',
  {
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    courseKey: text('course_key').notNull(),
    addedAt: timestamp('added_at').notNull().defaultNow(),
  },
  (t) => ({ pk: primaryKey({ columns: [t.userId, t.courseKey] }) }),
);

export type User = typeof user.$inferSelect;
export type InvitedEmail = typeof invitedEmails.$inferSelect;
export type CourseRequest = typeof courseRequests.$inferSelect;
export type PlayedCourse = typeof playedCourses.$inferSelect;
export type Course = typeof courses.$inferSelect;
export type NewCourse = typeof courses.$inferInsert;
export type Tee = typeof tees.$inferSelect;
export type NewTee = typeof tees.$inferInsert;
export type TeeHole = typeof teeHoles.$inferSelect;
export type NewTeeHole = typeof teeHoles.$inferInsert;
export type Round = typeof rounds.$inferSelect;
export type NewRound = typeof rounds.$inferInsert;
export type Shot = typeof shots.$inferSelect;
export type NewShot = typeof shots.$inferInsert;
